apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        env:
         - name: POSTGRES_DB
           valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: DB_NAME
         - name: POSTGRES_USER
           valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: DB_USER
         - name: POSTGRES_PASSWORD
           valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: DB_PASSWORD
         - name: POSTGRES_HOST
           valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: DB_HOST
         - name: POSTGRES_PORT
           valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: DB_PORT
         - name: POSTGRES_SSL
           valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: DB_SSL
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432